# Generated by Django 4.0.5 on 2022-10-03 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sentence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='text')),
                ('reads_count', models.IntegerField(verbose_name='reads count')),
                ('is_valid', models.BooleanField(verbose_name='boolean')),
                ('invalidity_reason', models.IntegerField(choices=[(0, 'Not Correct Sentence'), (1, 'Other invalidities')], verbose_name='Integer')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
