# Generated by Django 4.0.5 on 2022-10-03 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_rename_td_id_user_tg_id'),
        ('sentence', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sentence',
            options={'verbose_name': 'Sentence', 'verbose_name_plural': 'Sentences'},
        ),
        migrations.AddField(
            model_name='sentence',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='user.user', verbose_name='Author'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sentence',
            name='invalidity_reason',
            field=models.IntegerField(choices=[(0, 'Not Correct Sentence'), (1, 'Other invalidities')], verbose_name='Invalidity reason'),
        ),
        migrations.AlterField(
            model_name='sentence',
            name='is_valid',
            field=models.BooleanField(verbose_name='Is valid'),
        ),
        migrations.AlterField(
            model_name='sentence',
            name='reads_count',
            field=models.IntegerField(verbose_name='Reads count'),
        ),
        migrations.AlterField(
            model_name='sentence',
            name='text',
            field=models.TextField(verbose_name='Text'),
        ),
    ]
