# Generated by Django 4.0.5 on 2022-10-03 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentence', '0002_alter_sentence_options_sentence_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentence',
            name='invalidity_reason',
            field=models.IntegerField(choices=[(0, 'Not correct sentence'), (1, 'Other invalidities'), (2, 'Unknown yet')], default=2, verbose_name='Invalidity reason'),
        ),
        migrations.AlterField(
            model_name='sentence',
            name='is_valid',
            field=models.BooleanField(default=True, verbose_name='Is valid'),
        ),
        migrations.AlterField(
            model_name='sentence',
            name='reads_count',
            field=models.IntegerField(default=0, verbose_name='Reads count'),
        ),
    ]
