# Generated by Django 4.0.5 on 2022-10-03 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_rename_td_id_user_tg_id'),
        ('voice', '0002_voice'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='voicechecker',
            options={'verbose_name': 'Voice checker', 'verbose_name_plural': 'Voice checkers'},
        ),
        migrations.AddField(
            model_name='voicechecker',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='user.user', verbose_name='Author'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='voicechecker',
            name='voice',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.RESTRICT, to='voice.voice', verbose_name='Voice'),
            preserve_default=False,
        ),
    ]
