# Generated by Django 4.1.1 on 2022-09-27 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(help_text='Please enter full name...', max_length=200)),
                ('td_id', models.PositiveIntegerField(help_text='Please enter td id...', max_length=20)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('year_of_birth', models.DateField(help_text='Please enter birth date...')),
                ('native_language', models.CharField(choices=[('Uz', 'Uz'), ('Ru', 'Ru'), ('Qq', 'Qq')], help_text='Please choose language...', max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
    ]
