# Generated by Django 4.1.1 on 2022-09-27 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(help_text='Please enter full name...', max_length=200)),
                ('td_id', models.PositiveIntegerField(help_text='Please enter td id...')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('year_of_birth', models.DateField(help_text='Please enter birth date...')),
                ('accent_region', models.CharField(choices=[('Andijon', 'Andijon'), ('Buxoro', 'Buxoro'), ("Farg'ona", 'Fargona'), ('Jizzax', 'Jizzax'), ('Xorazm', 'Xorazm'), ('Namangan', 'Namangan'), ('Navoiy', 'Navoiy'), ('Qashqadaryo', 'Qashqadaryo'), ("Qoraqalpog'iston", 'Qoraqalpogiston'), ('Samarqand', 'Samarqand'), ('Surxondaryo', 'Surxondaryo'), ('Toshkent viloyati', 'Toshkent'), ('Toshkent shahri', 'Toshkent Shahri')], help_text='Please enter region...', max_length=17)),
                ('native_language', models.CharField(choices=[('Uz', 'Uz'), ('Ru', 'Ru'), ('Qq', 'Qq')], help_text='Please choose language...', max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
    ]
