# Generated by Django 4.1.1 on 2022-09-27 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='td_id',
            field=models.PositiveIntegerField(help_text='Please enter td id...'),
        ),
    ]
