# Generated by Django 4.0.5 on 2022-10-03 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_accent_region'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='td_id',
            new_name='tg_id',
        ),
    ]
