# Generated by Django 4.1.1 on 2022-09-27 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_created_at_alter_user_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='accent_region',
        ),
        migrations.AlterField(
            model_name='user',
            name='full_name',
            field=models.CharField(help_text='Please enter full name...', max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='native_language',
            field=models.CharField(choices=[('Uz', 'Uz'), ('Ru', 'Ru'), ('Qr', 'Qr')], help_text='Please choose language...', max_length=2),
        ),
        migrations.AlterField(
            model_name='user',
            name='td_id',
            field=models.PositiveIntegerField(help_text='Please enter td id...', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='year_of_birth',
            field=models.DateField(help_text='Please enter birth date...'),
        ),
        migrations.DeleteModel(
            name='Foo',
        ),
    ]
